import {StyleSheet} from 'react-native';
import {Dimensions} from 'react-native';

const screenWidth = Dimensions.get('window').width;
const screenHeight = Dimensions.get('window').height;

const styles = StyleSheet.create({
  imageBackground1: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  image1: {
    height: 275,
    width: 275,
    marginTop: 50,
  },
  image2: {
    height: 125,
    width: 125,
    marginRight: 10,
    marginTop: 10,
  },
  image3: {
    height: 125,
    width: 125,
    marginLeft: 10,
    marginTop: 10,
  },
  image4: {
    height: 25,
    width: 25,
  },
  textInput1: {
    backgroundColor: '#0c0b09',
    color: '#eee7da',
    width: 175,
    marginHorizontal: 10,
    borderRadius: 10,
    minHeight: 40,
    borderWidth: 1,
    borderColor: 'black',
    textAlign: 'center',
    fontFamily: 'Vonique64',
  },
  textInput2: {
    textAlign: 'center',
    width: 175,
    backgroundColor: '#0c0b09',
    color: '#eee7da',
    marginHorizontal: 10,
    marginBottom: 10,
    marginTop: 5,
    borderRadius: 10,
    minHeight: 40,
    borderWidth: 1,
    borderColor: 'black',
    fontFamily: 'Vonique64',
  },
  touchable1: {
    backgroundColor: '#b6e7cc',
    minHeight: 35,
    justifyContent: 'center',
    borderRadius: 10,
    marginHorizontal: 10,
    marginTop: 10,
    marginBottom: 10,
  },
  touchable2: {
    backgroundColor: '#b6e7cc',
    minHeight: 35,
    justifyContent: 'center',
    borderRadius: 10,
    marginBottom: 80,
    marginTop: 10,
  },
  touchable3: {
    backgroundColor: '#fb445c',
    minHeight: 35,
    justifyContent: 'center',
    borderRadius: 10,
    marginTop: 10,
  },
  touchable4: {
    alignSelf: 'flex-end',
  },
  text1: {
    color: '#0c0b09',
    fontSize: 14,
    textAlign: 'center',
    fontFamily: 'Vonique64',
    marginTop: 5,
  },
  text2: {
    color: '#0c0b09',
    fontSize: 12,
    fontFamily: 'Vonique64',
    textAlign: 'center',
  },
  text3: {
    color: '#0c0b09',
    fontSize: 12,
    textAlign: 'center',
    marginLeft: 10,
    marginRight: 10,
    marginTop: 5,
    fontFamily: 'Vonique64',
  },
  text4: {
    textAlign: 'center',
    color: '#0c0b09',
    marginTop: 60,
    marginBottom: 50,
    fontFamily: 'HighTide-Sans',
  },
  text5: {
    color: '#0c0b09',
    fontSize: 12,
    textAlign: 'center',
    marginLeft: 10,
    marginRight: 10,
    marginTop: 5,
    fontFamily: 'Vonique64',
  },
  text6: {
    color: '#0c0b09',
    fontSize: 12,
    textAlign: 'center',
    marginLeft: 10,
    marginRight: 10,
    marginTop: 10,
    fontFamily: 'Vonique64',
  },
  view1: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  view2: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  view3: {
    backgroundColor: '#b6e7cc',
    minHeight: 300,
    width: '80%',
    borderRadius: 5,
    padding: 20,
  },
  view4: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  view5: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  view6: {
    backgroundColor: '#b6e7cc',
    minHeight: 300,
    width: '80%',
    borderRadius: 5,
    padding: 20,
  },
  view7: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  textInput3: {
    backgroundColor: '#0c0b09',
    color: '#eee7da',
    width: 175,
    marginBottom: 10,
    marginTop: 40,
    borderRadius: 10,
    minHeight: 40,
    borderWidth: 1,
    borderColor: 'black',
    textAlign: 'center',
    fontFamily: 'Vonique64',
  },
  textInput4: {
    backgroundColor: '#0c0b09',
    color: '#eee7da',
    width: 175,
    marginHorizontal: 10,
    borderRadius: 10,
    minHeight: 40,
    borderWidth: 1,
    borderColor: 'black',
    textAlign: 'center',
    fontFamily: 'Vonique64',
  },
  textInput5: {
    backgroundColor: '#fb445c',
    minHeight: 35,
    alignSelf: 'center',
    borderRadius: 10,
    marginTop: 10,
    width: screenWidth * 0.4,
  },
  textInput: {
    fontFamily: 'HighTide-Sans',
    backgroundColor: '#eee7da',
    alignSelf: 'center',
    margin: 10,
    borderRadius: 5,
    minHeight: 50,
    borderWidth: 1,
    borderColor: '#5A6472',
    borderBottomWidth: 3,
    width: screenWidth * 0.6,
  },
});
export default styles;
