import {Dimensions, StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  view1: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#eee7da',
    padding: 8,
    marginVertical: 8,
    marginBottom: 20,
    borderRadius: 8,
  },
  view2: {
    alignItems: 'flex-end',
    flexDirection: 'row',
  },
  view3: {
    flexDirection: 'column',
  },
  view4: {
    alignItems: 'flex-end',
    flex: 1,
  },
  view5: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-end',
    backgroundColor: '#b6e7cc',
    borderRadius: 8,
    maxHeight: 40,
    maxWidth: 100,
  },
  view6: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  view7: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#eee7da99',
    padding: 8,
    marginTop: 10,
    marginVertical: 8,
    borderRadius: 8,
    minWidth: '90%',
  },
  view8: {
    alignItems: 'flex-end',
    flexDirection: 'row',
  },
  view9: {
    flexDirection: 'column',
  },
  view10: {
    flex: 1,
    alignItems: 'flex-end',
  },
  view11: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-end',
    backgroundColor: '#b6e7cc98',
    borderRadius: 8,
    maxHeight: 40,
    maxWidth: 100,
  },
  view12: {
    flex: 1,
    justifyContent: 'flex-start',
    padding: 8,
    borderRadius: 5,
  },
  view13: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  image1: {
    height: 30,
    width: 30,
    borderRadius: 50,
    margin: 5,
  },
  image2: {
    height: 30,
    width: 30,
    borderRadius: 50,
    margin: 5,
    opacity: 0.7,
  },
  text3: {
    fontSize: 16,
    fontFamily: 'HighTide-Sans',
  },
  text4: {
    fontSize: 16,
    fontFamily: 'HighTide-Sans',
    marginBottom: 10,
  },
  text5: {
    fontSize: 12,
    fontFamily: 'HighTide-Sans',
    opacity: 0.4,
    marginBottom: 5,
  },
  text6: {
    fontSize: 12,
    fontFamily: 'HighTide-Sans',
    opacity: 0.6,
  },
  text7: {
    fontSize: 12,
    marginRight: 5,
    marginBottom: 5,
    fontFamily: 'HighTide-Sans',
    width: 50,
  },
  text8: {
    marginLeft: 5,
    marginTop: 10,
    fontSize: 8,
    fontFamily: 'HighTide-Sans',
    opacity: 0.7,
  },
  text9: {
    marginLeft: 5,
    marginTop: 10,
    fontSize: 8,
    fontFamily: 'HighTide-Sans',
    opacity: 0.7,
  },
  text10: {
    fontSize: 16,
    fontFamily: 'HighTide-Sans',
  },
  text11: {
    fontSize: 16,
    fontFamily: 'HighTide-Sans',
    marginBottom: 10,
  },
  text12: {
    fontSize: 12,
    fontFamily: 'HighTide-Sans',
    opacity: 0.4,
    marginBottom: 5,
  },
  text13: {
    fontSize: 12,
    fontFamily: 'HighTide-Sans',
    opacity: 0.6,
  },
  text14: {
    fontSize: 12,
    marginLeft: 5,
    marginRight: 5,
    marginBottom: 5,
    fontFamily: 'HighTide-Sans',
    opacity: 0.7,
    width: 50,
  },
  text15: {
    fontSize: 18,
    textAlign: 'center',
    marginBottom: 10,
    marginTop: 20,
    fontFamily: 'HighTide-Sans',
  },
  text16: {
    color: '#0c0b09',
    fontSize: 12,
    textAlign: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 15,
    marginBottom: 15,
    fontFamily: 'HighTide-Sans',
  },
  text17: {
    color: '#0c0b09',
    fontSize: 12,
    textAlign: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 15,
    marginBottom: 15,
    fontFamily: 'HighTide-Sans',
  },
  text18: {
    color: '#0c0b09',
    fontSize: 12,
    marginBottom: 10,
    marginTop: 10,
    marginRight: 10,
    marginLeft: 10,
    textAlign: 'center',
    fontFamily: 'HighTide-Sans',
  },
  text19: {
    color: '#0c0b09',
    fontSize: 21,
    textAlign: 'center',
    fontFamily: 'HighTide-Sans',
  },
  text20: {
    textAlign: 'center',
    color: '#0c0b09',
    fontSize: 18,
    fontFamily: 'HighTide-Sans',
  },
  text21: {
    textAlign: 'center',
    color: '#0c0b09',
    fontSize: 18,
    borderRadius: 5,
    fontFamily: 'HighTide-Sans',
  },
  container: {
    flex: 1,
    padding: 16,
    borderColor: '#b6e7cc',
    borderWidth: 3,
    borderRadius: 5,
  },
  messageContainer: {
    alignItems: 'flex-end',
    backgroundColor: '#e0e0e0',
    padding: 5,
    marginVertical: 8,
    borderRadius: 8,
  },
  messageText: {
    fontSize: 16,
  },
  inputContainer: {
    backgroundColor: '#eee7da',
    height: 90,
    justifyContent: 'flex-start',
    borderRadius: 8,
  },
  input2: {
    height: 90,
    padding: 8,
    borderWidth: 1,
    borderColor: '#ccc',
    fontFamily: 'HighTide-Sans',
  },
  modalView5: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalView6: {
    borderColor: '#0c0b09',
    backgroundColor: '#b6e7cc',
    minHeight: 300,
    width: '80%',
    justifyContent: 'center',
    borderRadius: 5,
    padding: 20,
  },
  modalView1: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalView2: {
    borderColor: '#0c0b09',
    backgroundColor: '#b6e7cc',
    minHeight: 300,
    width: '80%',
    justifyContent: 'center',
    borderRadius: 5,
    padding: 20,
  },
  modalView3: {
    flex: 1,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalView4: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  text1: {
    borderRadius: 5,
    marginTop: 10,
    marginLeft: 10,
    marginBottom: 10,
    fontFamily: 'HighTide-Sans',
  },
  text2: {
    borderRadius: 5,
    marginTop: 10,
    marginLeft: 10,
    marginBottom: 10,
    fontFamily: 'HighTide-Sans',
  },
  redTab: {
    position: 'absolute',
    bottom: 5,
    left: '5%',
    width: '90%',
    height: 20,
    backgroundColor: '#eee7da99',
    borderRadius: 5,
  },
  imageBackground1: {
    flex: 1,
  },
  imageBackground2: {
    opacity: 0.3,
  },
  touchable1: {
    backgroundColor: '#b6e7cc',
    borderRadius: 5,
    width: 100,
    borderWidth: 1,
    marginTop: 10,
    borderColor: '#eee7da',
  },
  touchable2: {
    backgroundColor: '#b6e7cc',
    borderRadius: 5,
    width: 100,
    borderWidth: 1,
    marginTop: 10,
    borderColor: '#eee7da',
  },
  touchable3: {
    marginTop: 20,
    backgroundColor: '#e7b6cc',
    minHeight: 50,
    justifyContent: 'center',
    borderRadius: 5,
    marginHorizontal: 10,
    width: 120,
  },
  touchable4: {
    marginTop: 20,
    backgroundColor: '#e7b6cc',
    minHeight: 50,
    justifyContent: 'center',
    borderRadius: 5,
    marginHorizontal: 10,
    width: 120,
  },
});

export default styles;
