import {Dimensions, StyleSheet} from 'react-native';
const screenWidth = Dimensions.get('window').width;
const screenHeight = Dimensions.get('window').height;

const styles = StyleSheet.create({
  view1: {
    flex: 1,
    backgroundColor: '#eee7da',
  },
  scrollView1: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  view2: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  touchable1: {
    backgroundColor: '#b6e7cc',
    marginTop: 10,
    width: screenWidth * 0.8,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#eee7da',
  },
  touchable2: {
    backgroundColor: '#b6e7cc',
    marginTop: 10,
    width: screenWidth * 0.8,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#eee7da',
  },
  touchable3: {
    backgroundColor: '#b6e7cc',
    marginTop: 10,
    marginBottom: 10,
    width: screenWidth * 0.8,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#eee7da',
  },
  touchable4: {
    backgroundColor: '#b6e7cc',
    marginLeft: 10,
    marginTop: 10,
    width: 250,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#eee7da',
  },
  view3: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  image1: {
    height: 30,
    width: 40,
  },
  image2: {
    width: 40,
    height: 40,
    marginLeft: 10,
  },
  image3: {
    width: 40,
    height: 40,
    marginLeft: 10,
  },
  image4: {
    width: 40,
    height: 40,
    marginLeft: 10,
  },
  image5: {
    width: 40,
    height: 40,
    marginLeft: 10,
  },
  text3: {
    marginLeft: 10,
    marginTop: 10,
    fontFamily: 'HighTide-Sans',
  },
  text4: {
    fontFamily: 'Vonique64',
  },
  text5: {
    fontFamily: 'Vonique64',
  },
  text6: {
    fontFamily: 'Vonique64',
  },
  text7: {
    fontFamily: 'Vonique64',
  },
  text8: {
    fontFamily: 'Vonique64',
  },
  text9: {
    fontFamily: 'Vonique64',
  },
  text10: {
    fontFamily: 'Vonique64',
  },
  text11: {
    color: '#0c0b09',
    fontSize: 12,
    fontWeight: '600',
    margin: 10,
    textAlign: 'center',
    fontFamily: 'HighTide-Sans',
  },
  text12: {
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 10,
    fontFamily: 'Vonique64',
  },
  text13: {
    marginLeft: 10,
    marginTop: 5,
    fontSize: 20,
    fontFamily: 'Vonique64',
  },
  text14: {
    marginLeft: 10,
    marginTop: 5,
    fontSize: 20,
    fontFamily: 'Vonique64',
  },
  text15: {
    fontFamily: 'HighTide-Sans',
    marginLeft: 25,
    marginTop: 10,
  },
  text16: {
    marginLeft: 25,
    marginTop: 10,
    fontFamily: 'HighTide-Sans',
  },
  text17: {
    marginLeft: 25,
    marginTop: 10,
    fontWeight: '600',
    fontFamily: 'HighTide-Sans',
  },
  view4: {
    flex: 1,
    flexDirection: 'row',
    marginLeft: 10,
    marginRight: 10,
    marginTop: 10,
    backgroundColor: '#b6e7cc',
    borderRadius: 5,
  },
  view5: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#b6e7cc',
    margin: 10,
    borderRadius: 5,
  },
  view6: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#b6e7cc',
    marginLeft: 10,
    marginRight: 10,
    borderRadius: 5,
  },
  view7: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#b6e7cc',
    margin: 10,
    borderRadius: 5,
  },
  view8: {
    marginLeft: 10,
    marginRight: 10,
    backgroundColor: '#b6e7cc',
    borderRadius: 5,
  },
  view9: {
    backgroundColor: '#b6e7cc',
    margin: 10,
    borderRadius: 5,
  },
  view10: {
    backgroundColor: '#eee7da',
    margin: 10,
    borderRadius: 5,
  },
  view11: {
    flex: 1,
    alignItems: 'center',
  },
  view12: {
    flex: 1,
  },
  view13: {
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  view14: {
    flex: 1,
    marginTop: 10,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  view15: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  view16: {
    flex: 1,
    alignSelf: 'flex-start',
  },
  view17: {
    flex: 1,
    alignSelf: 'flex-start',
  },
  circleBefore: {
    marginTop: 20,
    marginBottom: 20,
    alignItems: 'center',
    justifyContent: 'center',
    width: 50,
    height: 50,
    borderRadius: 100 / 2,
    backgroundColor: '#eee7da',
    borderWidth: 1,
  },
  circleAfter: {
    marginTop: 20,
    marginBottom: 20,
    alignItems: 'center',
    justifyContent: 'center',
    width: 50,
    height: 50,
    borderRadius: 100 / 2,
    backgroundColor: 'green',
  },
  backgroundBefore: {
    height: 125,
    width: 125,
    borderRadius: 5,
  },
  backgroundAfter: {
    height: 125,
    width: 125,
    borderRadius: 5,
    borderWidth: 5,
    borderColor: '#f86ca7',
  },
  nestedView1: {
    flex: 1,
    alignItems: 'center',
    width: '100%',
  },
  nestedView2: {
    backgroundColor: '#eee7da',
    margin: 10,
    borderRadius: 5,
  },
  nestedView3: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginLeft: 10,
    marginRight: 10,
    marginTop: 20,
    backgroundColor: '#eee7da',
    borderRadius: 5,
  },
  nestedView4: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginLeft: 10,
    marginRight: 10,
    marginTop: 10,
    backgroundColor: '#eee7da',
    borderRadius: 5,
  },
  nestedView5: {
    flex: 1,
    marginTop: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  nestedView6: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  modalView1: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalView2: {
    borderColor: '#0c0b09',
    backgroundColor: '#b6e7cc',
    minHeight: 300,
    width: '80%',
    justifyContent: 'center',
    borderRadius: 5,
    padding: 20,
  },
  modalView3: {
    flex: 1,
    borderRadius: 5,
    marginTop: 20,
    // backgroundColor: '#f2f2f2',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalView4: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  modalView5: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalView6: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-evenly',
    backgroundColor: '#b6e7cc',
    height: 300,
    width: '80%',
    borderRadius: 5,
  },
  text1: {
    borderRadius: 5,
    marginTop: 10,
    marginBottom: 10,
    textAlign: 'center',
    fontFamily: 'HighTide-Sans',
  },
  text2: {
    borderRadius: 5,
    marginTop: 10,
    marginBottom: 10,
    textAlign: 'center',
    fontFamily: 'HighTide-Sans',
  },
});

export default styles;
