import {Dimensions, StyleSheet} from 'react-native';
const screenWidth = Dimensions.get('window').width;
const screenHeight = Dimensions.get('window').height;

const styles = StyleSheet.create({
  view1: {
    flex: 1,
    backgroundColor: '#eee7da',
  },
  scrollView1: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  view2: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  touchable1: {
    backgroundColor: '#b6e7cc',
    marginTop: 10,
    width: screenWidth * 0.8,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#eee7da',
  },
  touchable2: {
    backgroundColor: '#b6e7cc',
    marginTop: 10,
    width: screenWidth * 0.8,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#eee7da',
  },
  touchable3: {
    backgroundColor: '#b6e7cc',
    marginTop: 10,
    marginBottom: 10,
    width: screenWidth * 0.8,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#eee7da',
  },
  touchable4: {
    backgroundColor: '#b6e7cc',
    marginLeft: 10,
    marginTop: 10,
    width: 250,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#eee7da',
  },
  touchable5: {
    backgroundColor: '#b6e7cc',
    marginBottom: 10,
    width: screenWidth * 0.8,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#eee7da',
  },
  touchable6: {
    backgroundColor: '#e7b6cc',
    borderRadius: 5,
    marginLeft: screenWidth * 0.72,
    marginBottom: 20,
    width: 100,
    borderWidth: 1,
    borderColor: '#eee7da',
  },
  touchable7: {
    backgroundColor: '#e7b6cc',
    minHeight: 50,
    width: screenWidth * 0.7,
    justifyContent: 'center',
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#eee7da',
    marginHorizontal: 10,
    marginTop: 10,
    marginBottom: 10,
    alignSelf: 'center',
  },
  touchable8: {
    backgroundColor: '#e7b6cc',
    borderRadius: 5,
    margin: 10,
    width: 100,
    borderWidth: 2,
    borderColor: '#eee7da',
  },
  touchable9: {
    backgroundColor: '#e7b6cc',
    borderRadius: 5,
    margin: 10,
    width: 100,
    borderWidth: 2,
    borderColor: '#eee7da',
  },
  touchable10: {
    position: 'absolute',
    top: 10,
    right: 15,
  },
  touchable11: {
    marginTop: 50,
  },
  touchable12: {
    marginTop: 50,
  },
  touchable13: {
    marginTop: 50,
  },
  touchable14: {
    height: 100,
    width: screenWidth * 0.4,
    marginRight: 10,
    marginTop: 75,
    marginLeft: 10,
    backgroundColor: '#eee7da',
    borderRadius: 5,
  },
  touchable15: {
    height: 100,
    width: screenWidth * 0.4,
    marginRight: 10,
    marginTop: 60,
    marginLeft: 10,
    backgroundColor: '#eee7da',
    borderRadius: 5,
  },
  touchable16: {
    backgroundColor: '#b6e7cc',
    borderRadius: 5,
    margin: 10,
    width: 100,
    borderWidth: 1,
    borderColor: '#eee7da',
  },
  touchable17: {
    backgroundColor: '#b6e7cc',
    borderRadius: 5,
    margin: 10,
    width: 100,
    borderWidth: 1,
    borderColor: '#eee7da',
  },
  view3: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  image1: {
    height: 30,
    width: 40,
  },
  image2: {
    width: 40,
    height: 40,
    marginLeft: 10,
  },
  image3: {
    width: 40,
    height: 40,
    marginLeft: 10,
  },
  image4: {
    width: 40,
    height: 40,
    marginLeft: 10,
  },
  image5: {
    width: 40,
    height: 40,
    marginLeft: 10,
  },
  image6: {
    height: 75,
    width: 75,
    borderRadius: 5,
  },
  image7: {
    height: 75,
    width: 75,
    borderRadius: 5,
  },
  image8: {
    height: 75,
    width: 75,
    borderRadius: 5,
  },
  image9: {
    height: 75,
    width: 75,
    borderRadius: 5,
  },
  image10: {
    height: 75,
    width: 75,
    borderRadius: 5,
  },
  image11: {
    height: 75,
    width: 75,
    borderRadius: 5,
  },
  image12: {
    height: 25,
    width: 25,
  },
  text3: {
    marginLeft: 10,
    marginTop: 10,
    fontFamily: 'HighTide-Sans',
  },
  text4: {
    fontFamily: 'Vonique64',
  },
  text5: {
    fontFamily: 'Vonique64',
  },
  text6: {
    fontFamily: 'Vonique64',
  },
  text7: {
    fontFamily: 'Vonique64',
  },
  text8: {
    fontFamily: 'Vonique64',
  },
  text9: {
    fontFamily: 'Vonique64',
  },
  text10: {
    fontFamily: 'Vonique64',
  },
  text11: {
    color: '#0c0b09',
    fontSize: 12,
    fontWeight: '600',
    margin: 10,
    textAlign: 'center',
    fontFamily: 'HighTide-Sans',
  },
  text12: {
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 10,
    fontFamily: 'Vonique64',
  },
  text13: {
    marginLeft: 10,
    marginTop: 5,
    fontSize: 20,
    fontFamily: 'Vonique64',
  },
  text14: {
    marginLeft: 10,
    marginTop: 5,
    fontSize: 20,
    fontFamily: 'Vonique64',
  },
  text15: {
    fontFamily: 'HighTide-Sans',
    marginLeft: 25,
    marginTop: 10,
  },
  text16: {
    marginLeft: 25,
    marginTop: 10,
    fontFamily: 'HighTide-Sans',
  },
  text17: {
    marginLeft: 25,
    marginTop: 10,
    fontWeight: '600',
    fontFamily: 'HighTide-Sans',
  },
  text18: {
    marginLeft: 25,
    marginTop: 10,
    fontFamily: 'HighTide-Sans',
  },
  text19: {
    marginLeft: 25,
    marginTop: 10,
    fontFamily: 'HighTide-Sans',
  },
  text20: {
    borderRadius: 5,
    marginTop: 10,
    marginBottom: 10,
    textAlign: 'left',
    fontFamily: 'HighTide-Sans',
  },
  text21: {
    marginLeft: 10,
    marginTop: 10,
    fontFamily: 'HighTide-Sans',
    maxWidth: screenWidth * 0.7,
  },
  text22: {
    marginLeft: 10,
    marginTop: 10,
    fontFamily: 'HighTide-Sans',
    maxWidth: screenWidth * 0.7,
  },
  text23: {
    marginLeft: 10,
    marginTop: 10,
    fontFamily: 'HighTide-Sans',
    maxWidth: screenWidth * 0.7,
  },
  text24: {
    marginLeft: 10,
    marginTop: 10,
    marginBottom: 10,
    fontFamily: 'HighTide-Sans',
    maxWidth: screenWidth * 0.7,
  },
  text25: {
    marginLeft: 10,
    marginTop: 10,
    marginBottom: 10,
    fontFamily: 'HighTide-Sans',
    maxWidth: screenWidth * 0.7,
  },
  text26: {
    marginLeft: 10,
    marginBottom: 10,
    marginTop: 10,
    fontFamily: 'HighTide-Sans',
    maxWidth: screenWidth * 0.7,
  },
  text27: {
    marginLeft: 25,
    marginTop: 10,
    fontFamily: 'HighTide-Sans',
  },
  text28: {
    color: '#0c0b09',
    fontSize: 21,
    textAlign: 'center',
    fontFamily: 'HighTide-Sans',
  },
  text29: {
    textAlign: 'center',
    color: '#0c0b09',
    fontSize: 16,
    borderRadius: 5,
    marginLeft: 5,
    marginRight: 5,
    borderColor: '#0c0b09',
    fontFamily: 'HighTide-Sans',
  },
  text30: {
    textAlign: 'center',
    color: '#0c0b09',
    fontSize: 18,
    borderRadius: 5,
    marginLeft: 5,
    marginRight: 5,
    fontFamily: 'HighTide-Sans',
  },
  text31: {
    color: '#0c0b09',
    fontSize: 12,
    fontWeight: '600',
    margin: 10,
    textAlign: 'center',
    fontFamily: 'HighTide-Sans',
  },
  text32: {
    color: '#0c0b09',
    fontSize: 12,
    fontWeight: '600',
    margin: 10,
    textAlign: 'center',
    fontFamily: 'HighTide-Sans',
  },
  text33: {
    borderRadius: 5,
    textAlign: 'center',
    marginTop: 40,
    marginBottom: 10,
    fontFamily: 'HighTide-Sans',
    fontSize: 18,
  },
  text34: {
    borderRadius: 5,
    textAlign: 'center',
    marginTop: 40,
    marginBottom: 10,
    fontFamily: 'HighTide-Sans',
    fontSize: 18,
  },
  text35: {
    alignSelf: 'center',
    marginTop: 20,
    fontFamily: 'HighTide-Sans',
    fontSize: 18,
  },
  text36: {
    borderRadius: 5,
    textAlign: 'left',
    marginTop: 30,
    marginBottom: 10,
    marginLeft: 5,
    fontFamily: 'HighTide-Sans',
    fontSize: 18,
  },
  text37: {
    borderRadius: 5,
    textAlign: 'left',
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 5,
    fontFamily: 'HighTide-Sans',
    fontSize: 18,
  },
  text38: {
    color: '#0c0b09',
    fontSize: 12,
    fontWeight: '600',
    margin: 10,
    textAlign: 'center',
    fontFamily: 'HighTide-Sans',
  },
  text39: {
    color: '#0c0b09',
    fontSize: 12,
    fontWeight: '600',
    margin: 10,
    textAlign: 'center',
    fontFamily: 'HighTide-Sans',
  },
  textInput1: {
    fontFamily: 'HighTide-Sans',
    backgroundColor: '#eee7da',
    marginHorizontal: 10,
    marginBottom: 10,
    marginTop: 5,
    borderRadius: 5,
    minHeight: 50,
    borderWidth: 1,
    borderColor: '#5A6472',
    borderBottomWidth: 3,
    width: screenWidth * 0.9,
  },
  textInput2: {
    fontFamily: 'HighTide-Sans',
    backgroundColor: '#eee7da',
    marginHorizontal: 10,
    marginBottom: 10,
    marginTop: 5,
    borderRadius: 5,
    minHeight: 50,
    borderWidth: 1,
    borderColor: '#5A6472',
    borderBottomWidth: 3,
    width: screenWidth * 0.9,
  },
  textInput3: {
    fontFamily: 'HighTide-Sans',
    backgroundColor: '#eee7da',
    marginHorizontal: 10,
    marginBottom: 10,
    marginTop: 5,
    borderRadius: 5,
    minHeight: 50,
    borderWidth: 1,
    borderBottomWidth: 3,
    borderColor: '#5A6472',
    width: screenWidth * 0.9,
  },
  textInput4: {
    fontFamily: 'HighTide-Sans',
    backgroundColor: '#eee7da',
    marginHorizontal: 10,
    marginBottom: 10,
    marginTop: 5,
    borderRadius: 5,
    minHeight: 50,
    borderWidth: 1,
    borderBottomWidth: 3,
    borderColor: '#5A6472',
    width: screenWidth * 0.9,
  },
  textInput5: {
    fontFamily: 'HighTide-Sans',
    backgroundColor: '#eee7da',
    marginHorizontal: 10,
    marginBottom: 10,
    marginTop: 5,
    borderRadius: 5,
    minHeight: 50,
    borderWidth: 1,
    borderBottomWidth: 3,
    borderColor: '#5A6472',
    width: screenWidth * 0.9,
  },
  textInput6: {
    fontFamily: 'HighTide-Sans',
    backgroundColor: '#eee7da',
    marginBottom: 10,
    marginTop: 5,
    borderRadius: 5,
    minHeight: 50,
    borderWidth: 1,
    borderBottomWidth: 3,
    borderColor: '#5A6472',
    width: screenWidth * 0.9,
  },
  animated1: {
    marginTop: 20,
    height: 150,
    width: screenWidth * 0.9,
  },
  animated2: {
    height: 250,
    width: screenWidth * 0.7,
    marginBottom: 10,
    borderRadius: 5,
    borderColor: '#eee7da',
    borderWidth: 2,
  },
  animated3: {
    height: 250,
    width: screenWidth * 0.7,
    borderRadius: 5,
    marginBottom: 10,
  },
  animated4: {
    height: 300,
    width: screenWidth * 0.95,
    borderRadius: 5,
  },
  animated5: {
    height: 300,
    width: screenWidth * 0.95,
    borderRadius: 5,
    borderColor: '#eee7da',
    borderWidth: 2,
  },
  animated6: {
    height: 50,
    width: 50,
    borderRadius: 5,
    marginRight: 20,
  },
  animated7: {
    marginLeft: 23,
    height: 50,
    width: 50,
    borderRadius: 5,
  },
  view4: {
    flex: 1,
    flexDirection: 'row',
    marginLeft: 10,
    marginRight: 10,
    marginTop: 10,
    backgroundColor: '#b6e7cc',
    borderRadius: 5,
  },
  view5: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#b6e7cc',
    margin: 10,
    borderRadius: 5,
  },
  view6: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#b6e7cc',
    marginLeft: 10,
    marginRight: 10,
    borderRadius: 5,
  },
  view7: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#b6e7cc',
    margin: 10,
    borderRadius: 5,
  },
  view8: {
    marginLeft: 10,
    marginRight: 10,
    backgroundColor: '#b6e7cc',
    borderRadius: 5,
  },
  view9: {
    backgroundColor: '#b6e7cc',
    margin: 10,
    borderRadius: 5,
  },
  view10: {
    backgroundColor: '#eee7da',
    margin: 10,
    borderRadius: 5,
  },
  view11: {
    flex: 1,
    alignItems: 'center',
  },
  view12: {
    flex: 1,
  },
  view13: {
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  view14: {
    flex: 1,
    marginTop: 10,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  view15: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  view16: {
    flex: 1,
    alignSelf: 'flex-start',
  },
  view17: {
    flex: 1,
    alignSelf: 'flex-start',
  },
  view18: {
    backgroundColor: '#b6e7cc',
    margin: 10,
    borderRadius: 5,
  },
  view19: {
    flex: 1,
    alignSelf: 'flex-start',
  },
  view20: {
    flex: 1,
    alignSelf: 'flex-start',
  },
  view21: {
    flex: 1,
    alignSelf: 'flex-start',
  },
  view22: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-evenly',
    backgroundColor: '#b6e7cc',
    height: 400,
    width: '80%',
    borderRadius: 5,
  },
  view23: {
    marginTop: 20,
    backgroundColor: 'pink',
    maxHeight: screenHeight * 0.3,
    borderRadius: 10,
  },
  view24: {
    borderTopColor: '#b6e7cc',
    borderTopWidth: 3,
  },
  view25: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  flatList: {
    width: screenWidth * 0.6,
    marginTop: 10,
  },
  circleBefore: {
    marginTop: 20,
    marginBottom: 20,
    alignItems: 'center',
    justifyContent: 'center',
    width: 50,
    height: 50,
    borderRadius: 100 / 2,
    backgroundColor: '#eee7da',
    borderWidth: 1,
  },
  circleAfter: {
    marginTop: 20,
    marginBottom: 20,
    alignItems: 'center',
    justifyContent: 'center',
    width: 50,
    height: 50,
    borderRadius: 100 / 2,
    backgroundColor: 'green',
  },
  backgroundBefore: {
    height: 125,
    width: 125,
    borderRadius: 5,
  },
  backgroundAfter: {
    height: 125,
    width: 125,
    borderRadius: 5,
    borderWidth: 5,
    borderColor: '#f86ca7',
  },
  nestedView1: {
    flex: 1,
    alignItems: 'center',
    width: '100%',
  },
  nestedView2: {
    backgroundColor: '#eee7da',
    margin: 10,
    borderRadius: 5,
  },
  nestedView3: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginLeft: 10,
    marginRight: 10,
    marginTop: 20,
    backgroundColor: '#eee7da',
    borderRadius: 5,
  },
  nestedView4: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginLeft: 10,
    marginRight: 10,
    marginTop: 10,
    backgroundColor: '#eee7da',
    borderRadius: 5,
  },
  nestedView5: {
    flex: 1,
    marginTop: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  nestedView6: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  modalView1: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalView2: {
    borderColor: '#0c0b09',
    backgroundColor: '#b6e7cc',
    minHeight: 300,
    width: '80%',
    justifyContent: 'center',
    borderRadius: 5,
    padding: 20,
  },
  modalView3: {
    flex: 1,
    borderRadius: 5,
    marginTop: 20,
    // backgroundColor: '#f2f2f2',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalView4: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  modalView5: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalView6: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-evenly',
    backgroundColor: '#b6e7cc',
    height: 300,
    width: '80%',
    borderRadius: 5,
  },
  text1: {
    borderRadius: 5,
    marginTop: 10,
    marginBottom: 10,
    textAlign: 'center',
    fontFamily: 'HighTide-Sans',
  },
  text2: {
    borderRadius: 5,
    marginTop: 10,
    marginBottom: 10,
    textAlign: 'center',
    fontFamily: 'HighTide-Sans',
  },
});

export default styles;
