import {Dimensions, StyleSheet} from 'react-native';

const screenHeight = Dimensions.get('window').height;

const styles = StyleSheet.create({
  touchable1: {
    width: 20,
    height: 20,
    marginTop: 10,
  },
  touchable2: {
    backgroundColor: '#e7b6cc',
    borderRadius: 5,
    width: 100,
    borderWidth: 1,
    borderColor: '#eee7da',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  touchable3: {
    backgroundColor: '#e7b6cc',
    borderRadius: 50,
    width: 80,
    height: 80,
    margin: 20,
    borderWidth: 1,
    borderColor: '#eee7da',
    justifyContent: 'center',
    alignItems: 'center',
  },
  touchable4: {
    backgroundColor: '#e7b6cc',
    borderRadius: 5,
    width: 100,
    borderWidth: 1,
    borderColor: '#eee7da',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  touchable5: {
    alignSelf: 'flex-end',
  },
  image1: {
    width: 30,
    height: 30,
  },
  headerRight: {
    width: 30,
    height: 30,
    textAlign: 'right',
  },
  image2: {
    borderRadius: 5,
  },
  image3: {
    height: 25,
    width: 25,
  },
  imageBackground1: {
    flex: 1,
  },
  imageBackground2: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  view1: {
    flex: 1,
    backgroundColor: '#eee7da80',
    maxHeight: 50,
    width: 180,
    alignSelf: 'center',
    margin: 10,
    borderRadius: 8,
  },
  view2: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'absolute',
    bottom: 0,
    left: 15,
    right: 15,
  },
  view3: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  view4: {
    backgroundColor: '#b6e7cc',
    minHeight: 300,
    width: '80%',
    borderRadius: 5,
    padding: 20,
    marginTop: screenHeight * 0.2,
  },
  view5: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  text1: {
    fontSize: 24,
    textAlign: 'center',
    marginTop: 15,
    fontFamily: 'HighTide-Sans',
    opacity: 0.5,
  },
  text2: {
    fontFamily: 'HighTide-Sans',
  },
  text3: {
    color: '#0c0b09',
    textAlign: 'center',
    fontFamily: 'HighTide-Sans',
  },
  text4: {
    color: '#0c0b09',
    fontFamily: 'HighTide-Sans',
    textAlign: 'center',
  },
  text5: {
    color: '#0c0b09',
    fontFamily: 'HighTide-Sans',
    textAlign: 'center',
  },
  text6: {
    color: '#0c0b09',
    fontSize: 12,
    textAlign: 'center',
    marginLeft: 10,
    marginRight: 10,
    marginTop: 5,
    fontFamily: 'Vonique64',
  },
  text7: {
    color: '#0c0b09',
    fontSize: 12,
    textAlign: 'center',
    marginLeft: 10,
    marginRight: 10,
    marginTop: 40,
    fontFamily: 'Vonique64',
  },
  text8: {
    marginTop: 20,
    color: '#0c0b09',
    fontFamily: 'HighTide-Sans',
    textAlign: 'center',
    fontSize: 20,
  },
  text9: {
    marginTop: 40,
    color: '#0c0b09',
    fontFamily: 'HighTide-Sans',
    textAlign: 'left',
    maxWidth: '90%',
  },
  text10: {
    color: '#0c0b09',
    fontSize: 12,
    fontWeight: '600',
    margin: 10,
    textAlign: 'center',
    fontFamily: 'HighTide-Sans',
  },
  textInput1: {
    fontFamily: 'HighTide-Sans',
    backgroundColor: '#eee7da',
    borderRadius: 5,
    height: 50,
    width: 150,
    borderWidth: 1,
    borderColor: '#5A6472',
    borderBottomWidth: 3,
    marginTop: 40,
    textAlign: 'center',
  },
  textInput2: {
    backgroundColor: '#e7b6cc',
    borderRadius: 5,
    width: 100,
    borderWidth: 1,
    borderColor: '#eee7da',
    marginTop: 80,
  },
});

export default styles;
